[package]
name = "las-poly"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }
geo = "0.28.0"
geojson = "0.24.1"
las = "0.9.1"
num_cpus = "1.16.0"
proj = "0.27.2"
rand = "0.8.5"
serde_json = "1.0.128"
threadpool = "1.8.1"
walkdir = "2.5.0"
