name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  proj-ubuntu:
    name: proj ubuntu
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - run: sudo apt-get update && sudo apt-get install -y libproj-dev
      - run: cargo build --release
      - run: cargo test
  proj-macos:
    name: proj macos
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies (macOS)
        run: brew install proj

      - run: cargo build --release
      - run: cargo test
       
  proj-windows:
    name: proj windows
    runs-on: 'windows-latest'
    env:
      PKG_CONFIG_PATH: C:\vcpkg\installed\x64-windows\lib\pkgconfig
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies (Windows)
        run: |
          choco install pkgconfiglite -y
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg.exe install proj:x64-windows
          echo "$env:GITHUB_WORKSPACE\vcpkg\installed\x64-windows\bin" >> $GITHUB_PATH
          echo "PKG_CONFIG_PATH=$env:GITHUB_WORKSPACE\vcpkg\installed\x64-windows\lib\pkgconfig" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$env:PKG_CONFIG_PATH"
          echo "PATH=$env:PATH"

      - name: Build
        run: cargo build --release

      - name: Run tests
        run: cargo test
